/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardSpotlight: typeof import('./src/components/ui/card-spotlight/CardSpotlight.vue')['default']
    GlareCard: typeof import('./src/components/ui/glare-card/GlareCard.vue')['default']
    GlobalLoader: typeof import('./src/components/GlobalLoader.vue')['default']
    Marquee: typeof import('./src/components/ui/marquee/Marquee.vue')['default']
    ParticlesBg: typeof import('./src/components/ui/particles-bg/ParticlesBg.vue')['default']
    ReviewCard: typeof import('./src/components/ui/marquee/ReviewCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShProductCard: typeof import('./src/components/shProductCard.vue')['default']
    ToggleFavoriteBtn: typeof import('./src/components/ToggleFavoriteBtn.vue')['default']
    Vortex: typeof import('./src/components/ui/vortex/Vortex.vue')['default']
  }
}
