/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/aboutUs': RouteRecordInfo<'/aboutUs', '/aboutUs', Record<never, never>, Record<never, never>>,
    '/logInSingUp': RouteRecordInfo<'/logInSingUp', '/logInSingUp', Record<never, never>, Record<never, never>>,
    '/member': RouteRecordInfo<'/member', '/member', Record<never, never>, Record<never, never>, '/member/' | '/member/beingHost' | '/member/cart' | '/member/favorites' | '/member/orders' | '/member/profile' | '/member/socials'>,
    '/member/': RouteRecordInfo<'/member/', '/member', Record<never, never>, Record<never, never>>,
    '/member/beingHost': RouteRecordInfo<'/member/beingHost', '/member/beingHost', Record<never, never>, Record<never, never>>,
    '/member/cart': RouteRecordInfo<'/member/cart', '/member/cart', Record<never, never>, Record<never, never>>,
    '/member/favorites': RouteRecordInfo<'/member/favorites', '/member/favorites', Record<never, never>, Record<never, never>>,
    '/member/orders': RouteRecordInfo<'/member/orders', '/member/orders', Record<never, never>, Record<never, never>>,
    '/member/profile': RouteRecordInfo<'/member/profile', '/member/profile', Record<never, never>, Record<never, never>>,
    '/member/socials': RouteRecordInfo<'/member/socials', '/member/socials', Record<never, never>, Record<never, never>>,
    '/shop': RouteRecordInfo<'/shop', '/shop', Record<never, never>, Record<never, never>>,
    '/socials': RouteRecordInfo<'/socials', '/socials', Record<never, never>, Record<never, never>>,
    '/venueList': RouteRecordInfo<'/venueList', '/venueList', Record<never, never>, Record<never, never>>,
    '/venueSingle/[id]': RouteRecordInfo<'/venueSingle/[id]', '/venueSingle/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
